# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Private Key management deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Connecting to remote
      uses: appleboy/ssh-action@v0.1.2
      with:
        PASSWORD: ${{secrets.PRIVATE_PASSWORD}}
        HOST: ${{secrets.PRIVATE_HOST}}
        USERNAME: ${{secrets.PRIVATE_USERNAME}}
        PORT: ${{secrets.PRIVATE_PORT}}
        script: |
          pm2 stop /home/bnaniance/private_key_api/server.js
          rm -rf /home/bnaniance/private_key_api
          cd /home/bnaniance
          git clone https://github.com/timothy-odofin/private_key_api.git
          cd /home/bnaniance/private_key_api
          npm install
          pm2 start server.js
